### PR TITLE
Warnings fix

### PR DESCRIPTION
**Pull request by AronBuzogany**
This PR proposes a solution for #69 it does the following:

- It was previously known that `react-scripts`, which also configured the `webpack` configuration caused some errors/warnings which we couldn't access. I have removed this and made our own configurations and scripts. 
- I have updated npm packages

Currently there are no more build warnings. There is however still an audit vulnerability, caused by cypress, this is an open and active issue https://github.com/cypress-io/cypress/issues/27261 in their repo. 

The warnings on the client side is also an open issue on their end, I have made a separate issue #70  so we can follow up.

### CODE REVIEW

**Review by pheyvaer — CHANGES_REQUESTED** [review]
When running the tests I get this error

```shell
sh: react-scripts: command not found
```

**Review by pheyvaer — COMMENTED** [review]
Do all tests pass for you? For me two of them fail:

- Log in and execute query on private data
- Query public data

Also package-lock.json has changes when I do `npm i`. This should not happen.

**Comment by AronBuzogany** [comment]
> Do all tests pass for you? For me two of them fail

I've just looked into it, those 2 fail due to #76 

> Also package-lock.json has changes when I do npm i. This should not happen.

Should be resolved now with [commit 6dbb572](https://github.com/SolidLabResearch/generic-data-viewer/pull/74/commits/6dbb572eaabf5455cc3816cbe5a0043b0613c40a)

**Comment by AronBuzogany** [comment]
> Do all tests pass for you?

Having resolved #76 now and merged with main, all tests succeed again. 

However cors-anywhere introduced another vulnaribility which is also an open issue on their end: 

https://github.com/Rob--W/cors-anywhere/issues/426

**Review by pheyvaer — APPROVED** [review]
Sometimes the second Cypress test fails, but I can't seem to consistently reproduce it. Might be something specific to my system, but in the long run it might be useful to have tests on GitHub directly.

**Comment by AronBuzogany** [comment]
> Sometimes the second Cypress test fails, but I can't seem to consistently reproduce it.

I have executed it locally a few times, but it always succeeds on my end. Cypress should save a screenshot in the `cypress/screenshots` folder of where it fails. Optionally you can also set `video` to `true` in `cypress.config.js` which will show a recording of where it fails. 

> Might be something specific to my system, but in the long run it might be useful to have tests on GitHub directly.

I could build a CI/CD Pipleline or is this not what you had in mind?

**Comment by pheyvaer** [comment]
> I could build a CI/CD Pipleline or is this not what you had in mind?

Yes, but not important now. I will just make an issue to remember for the future.

**Pull request merged**
