### PR TITLE
Fix #20

### LINKED ISSUE #20: Comunica engine doesnt resolve promise
Using test query with id ```123``` in the [config file](https://github.com/SolidLabResearch/generic-data-viewer/blob/main/src/config.json), currently on branch [login-authentication](https://github.com/SolidLabResearch/generic-data-viewer/tree/login-authentication) we can reconstruct the following example cases. 

- Case 1
  - Execute query.
  - Results are shown, works as expected.
- Case 2
  - Log in.
  - Execute query.
  - No results are shown, the source doesn't allow authenticated fetch
- Case 3 
  - Log in.
  - Logout.
  - Execute query.
  - Results are shown, works as expected
- Case 4
  - Log in. 
  - Execute query.
  - No results are shown, the source doesn't allow authenticated fetch
  - Log out.
  - Execute query.
  - No response after engine.query(...), the promise doesn't resolve nor reject, infinite loop? 

The promise seems never to resolve or reject. I have found this by placing console.logs() after both cases, neither of them actually happened. 

I have also tested these cases on [Comunica jQuery widget](https://query.linkeddatafragments.org/). Although we cannot be sure, they seem to result in similar results.

### PR DESCRIPTION
**Pull request by AronBuzogany**
Thanks to a response on the issue opened in the Comunica repo, issue #20 is resolved

### CODE REVIEW

**Comment by pheyvaer** [comment]
I can't test this because of https://github.com/SolidLabResearch/generic-data-viewer/issues/76

**Comment by AronBuzogany** [comment]
> I can't test this because of https://github.com/SolidLabResearch/generic-data-viewer/issues/76

I have tested it by replacing the fetch function with 

```js
...
fetch: () => {throw new Error("fail")}
...
```
After refreshing a failed query, it fails again.

**Comment by pheyvaer** [comment]
> > I can't test this because of #76
> 
> I have tested it by replacing the fetch function with
> 
> ```js
> ...
> fetch: () => {throw new Error("fail")}
> ...
> ```
> 
> After refreshing a failed query, it fails again.

For development sure, but from my side I only test the code as it is. Thus, #76 has to be fixed first before I look into this PR.

**Comment by AronBuzogany** [comment]
As of #78 this now works and all tests succeed.

**Review by pheyvaer — APPROVED** [review]

**Pull request merged**
